# Generated by Django 6.0.4 on 2026-04-30 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_search_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
