# Generated by Django 6.0.4 on 2026-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_last_search_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_credits_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
